"""Authentication and RBAC configuration for the GIS API (Feature 6).

IMPORTANT -- read before relying on this in production
------------------------------------------------------
This project had NO authentication layer before Feature 6 (the README listed auth as out
of scope, and no module in app/ referenced tokens, users, roles, or permissions). There
was therefore nothing to reuse, so this module and app/api/security.py implement a
deliberately small bearer-token + role layer whose only job is to be a clean SEAM: routes
depend on `require_permission(...)`, never on how a caller was identified. Replacing this
with a real identity provider (OIDC/JWT, a session service, an API gateway) means
rewriting `resolve_principal` in app/api/security.py and nothing else.

What it does provide: opaque bearer tokens stored as SHA-256 hashes, mapped to roles,
mapped to permissions. What it does NOT provide: token expiry, refresh, revocation lists,
per-user rate limiting, audit trails, or password/credential handling. Do not extend this
into a full auth system -- replace it.

Default posture is FAIL-CLOSED: with no token registry configured, protected endpoints
return 503 rather than silently admitting everyone.
"""

from __future__ import annotations

import os
from enum import Enum
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[2]


class Permission(str, Enum):
    """What a caller is allowed to do with the GIS subsystem."""

    VIEW_GIS = "VIEW_GIS"
    """Read boundaries and past assessments."""

    RUN_GIS_ANALYSIS = "RUN_GIS_ANALYSIS"
    """Execute spatial collision analysis and record assessments."""

    MANAGE_GIS_DATA = "MANAGE_GIS_DATA"
    """Create, replace, or delete boundary records."""


class Role(str, Enum):
    """Coarse job-shaped bundles of permissions. Callers are assigned roles, not permissions."""

    GIS_VIEWER = "GIS_VIEWER"
    GIS_ANALYST = "GIS_ANALYST"
    GIS_ADMIN = "GIS_ADMIN"


# The single source of truth for who can do what. Roles are cumulative by convention but
# expressed explicitly, so a reader never has to infer inheritance.
ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    Role.GIS_VIEWER.value: frozenset({Permission.VIEW_GIS.value}),
    Role.GIS_ANALYST.value: frozenset({Permission.VIEW_GIS.value, Permission.RUN_GIS_ANALYSIS.value}),
    Role.GIS_ADMIN.value: frozenset(
        {Permission.VIEW_GIS.value, Permission.RUN_GIS_ANALYSIS.value, Permission.MANAGE_GIS_DATA.value}
    ),
}

# --- Token registry ----------------------------------------------------------------
# Tokens are never stored in plaintext, and never committed: the file below is
# gitignored and generated by scripts/generate_api_tokens.py, which prints each raw
# token exactly once.
TOKEN_REGISTRY_PATH = Path(
    os.environ.get("GIS_API_TOKENS_FILE") or (BACKEND_ROOT / "data" / "auth" / "api_tokens.json")
)

#: Environment variable holding the registry inline as JSON, for deployments that inject
#: secrets rather than mounting files. Takes precedence over the file.
TOKEN_REGISTRY_ENV_VAR = "GIS_API_TOKENS"

# --- Mode --------------------------------------------------------------------------
#: "token"    -- bearer token required (default, fail-closed).
#: "disabled" -- every request is granted DISABLED_MODE_ROLES. Local development only;
#:               it must be an explicit opt-in, never something a missing file falls back to.
AUTH_MODE = os.environ.get("GIS_AUTH_MODE", "token").strip().lower()
AUTH_MODE_TOKEN = "token"
AUTH_MODE_DISABLED = "disabled"

DISABLED_MODE_ROLES: tuple[str, ...] = (Role.GIS_ADMIN.value,)
DISABLED_MODE_PRINCIPAL_ID = "anonymous-dev"

# Minimum entropy for generated tokens, in bytes (scripts/generate_api_tokens.py).
TOKEN_BYTES = 32

# WWW-Authenticate challenge returned with a 401.
AUTH_SCHEME = "Bearer"


def permissions_for_roles(roles: tuple[str, ...] | list[str] | frozenset[str]) -> frozenset[str]:
    """Union of the permissions granted by a set of roles. Unknown roles grant nothing."""
    granted: set[str] = set()
    for role in roles:
        granted |= ROLE_PERMISSIONS.get(role, frozenset())
    return frozenset(granted)


def _validate() -> None:
    if AUTH_MODE not in {AUTH_MODE_TOKEN, AUTH_MODE_DISABLED}:
        raise ValueError(
            f"GIS_AUTH_MODE must be {AUTH_MODE_TOKEN!r} or {AUTH_MODE_DISABLED!r}, got {AUTH_MODE!r}."
        )
    known = {permission.value for permission in Permission}
    for role, granted in ROLE_PERMISSIONS.items():
        unknown = granted - known
        if unknown:
            raise ValueError(f"Role {role!r} grants unknown permissions: {sorted(unknown)}")
    if set(ROLE_PERMISSIONS) != {role.value for role in Role}:
        raise ValueError("ROLE_PERMISSIONS must define exactly the roles in the Role enum.")


_validate()
